"""Stage 1: Generate diverse task skeletons with few-shot prompting.

Produces lightweight (goal, category, difficulty, key_objects) tuples
over-generated by ~15% to allow Stage 4 filtering. Uses BM25 similarity
to reject near-duplicate goals within each batch and steers generation
toward underrepresented categories.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
import config
from src.task_schema import TaskSkeleton
from src.tinker_utils import sample_text_batch, parse_json_lenient
from src.bm25 import bm25_score

# ── Few-shot examples keyed by difficulty band ──────────────────────────

FEW_SHOT_EXAMPLES: dict[str, list[dict]] = {
    "easy": [
        {
            "goal_description": "Water a potted basil plant on the kitchen windowsill",
            "category": "gardening",
            "difficulty": 1,
            "key_objects": ["watering_can", "basil_plant"],
            "rooms": ["kitchen", "garden"],
        },
        {
            "goal_description": "Hang a freshly washed bath towel on the towel rack to dry",
            "category": "laundry",
            "difficulty": 2,
            "key_objects": ["bath_towel", "towel_rack"],
            "rooms": ["bathroom", "laundry_room"],
        },
        {
            "goal_description": "Set a single place setting for dinner with a plate, fork, knife, and glass",
            "category": "meal_preparation",
            "difficulty": 2,
            "key_objects": ["plate", "fork", "knife", "glass", "placemat"],
            "rooms": ["kitchen"],
        },
    ],
    "medium": [
        {
            "goal_description": "Make a peanut butter and jelly sandwich and plate it for lunch",
            "category": "meal_preparation",
            "difficulty": 4,
            "key_objects": ["bread", "peanut_butter", "jelly", "knife", "plate"],
            "rooms": ["kitchen"],
        },
        {
            "goal_description": "Clean and organize the bathroom vanity countertop",
            "category": "cleaning",
            "difficulty": 4,
            "key_objects": ["sponge", "spray_cleaner", "vanity", "organizer_tray"],
            "rooms": ["bathroom"],
        },
        {
            "goal_description": "Wash a small load of dark-colored clothes and hang them to dry",
            "category": "laundry",
            "difficulty": 3,
            "key_objects": ["dark_clothes", "washing_machine", "detergent", "drying_rack"],
            "rooms": ["laundry_room"],
        },
    ],
    "hard": [
        {
            "goal_description": "Prepare a simple vegetable stir-fry with rice from scratch",
            "category": "cooking_baking",
            "difficulty": 6,
            "key_objects": [
                "wok", "rice_cooker", "rice", "vegetables", "cutting_board",
                "knife", "cooking_oil", "soy_sauce",
            ],
            "rooms": ["kitchen"],
        },
        {
            "goal_description": "Assemble a flat-pack bookshelf following the instruction manual",
            "category": "furniture_assembly",
            "difficulty": 6,
            "key_objects": [
                "shelf_panels", "screws", "screwdriver", "instruction_manual",
                "wooden_dowels", "back_panel",
            ],
            "rooms": ["living_room", "garage"],
        },
        {
            "goal_description": "Replace a leaky faucet washer in the kitchen sink",
            "category": "home_repair",
            "difficulty": 5,
            "key_objects": [
                "wrench", "replacement_washer", "faucet", "plumber_tape",
                "bucket",
            ],
            "rooms": ["kitchen", "garage"],
        },
    ],
    "complex": [
        {
            "goal_description": "Bake a batch of chocolate chip cookies from scratch, from mixing to cooling",
            "category": "cooking_baking",
            "difficulty": 8,
            "key_objects": [
                "flour", "sugar", "butter", "eggs", "chocolate_chips",
                "mixing_bowl", "baking_sheet", "oven", "wire_rack",
            ],
            "rooms": ["kitchen"],
        },
        {
            "goal_description": "Deep-clean and reorganize the entire garage including sorting tools",
            "category": "organizing",
            "difficulty": 8,
            "key_objects": [
                "broom", "dustpan", "storage_bins", "toolbox", "shelf_unit",
                "label_maker", "trash_bags", "vacuum",
            ],
            "rooms": ["garage"],
        },
        {
            "goal_description": "Prepare the garden bed for spring planting including soil amendment and seed starting",
            "category": "gardening",
            "difficulty": 7,
            "key_objects": [
                "shovel", "compost", "garden_fork", "seed_packets",
                "seed_trays", "watering_can", "garden_gloves",
            ],
            "rooms": ["garden", "garage"],
        },
    ],
}


SKELETON_SYSTEM = """\
You are a household task designer creating scenarios for a cognitive science \
benchmark. Each scenario is a multi-step procedural task performed in a home. \
You produce diverse, realistic, clearly scoped tasks.

Respond with a JSON array only — no markdown fences, no commentary."""


def _difficulty_band(difficulty: int) -> str:
    if difficulty <= 2:
        return "easy"
    elif difficulty <= 4:
        return "medium"
    elif difficulty <= 6:
        return "hard"
    else:
        return "complex"


def _build_skeleton_prompt(
    category: str,
    difficulty: int,
    count: int,
    existing_goals: list[str],
) -> str:
    band = _difficulty_band(difficulty)
    examples = FEW_SHOT_EXAMPLES[band]
    examples_json = json.dumps(examples, indent=2)

    avoid_block = ""
    if existing_goals:
        sample = existing_goals[-20:]
        avoid_block = (
            "\n\nAVOID generating tasks similar to these already-created goals:\n"
            + "\n".join(f"- {g}" for g in sample)
        )

    return f"""\
Generate exactly {count} unique household task skeletons in the "{category}" category.
Each task must require exactly {difficulty} sequential steps to complete.

Here are example skeletons at a similar difficulty level (use these as style reference, do NOT copy them):
{examples_json}

Requirements:
- Each goal_description must be specific and distinct (not generic like "clean the house")
- key_objects: 2-{max(3, difficulty + 1)} objects essential to the task
- rooms: which rooms of the house are involved
- difficulty must be {difficulty}
- category must be "{category}"
- Make tasks realistic for a typical household{avoid_block}

Respond with a JSON array of {count} skeleton objects, each with fields:
goal_description, category, difficulty, key_objects, rooms

JSON array only:"""


def generate_skeletons(
    existing_goals: list[str] | None = None,
) -> list[TaskSkeleton]:
    """Generate task skeletons for the entire curriculum, diversity-aware."""
    existing_goals = existing_goals or []

    target_total = int(config.TOTAL_TASKS * config.OVERGENERATE_FACTOR)
    per_difficulty = math.ceil(target_total / len(config.DIFFICULTY_LEVELS))

    print(f"Stage 1: Generating ~{target_total} task skeletons "
          f"({per_difficulty} per difficulty level)...")

    all_skeletons: list[TaskSkeleton] = []
    skeleton_counter = 0
    collected_goals: list[str] = list(existing_goals)

    for difficulty in config.DIFFICULTY_LEVELS:
        needed = per_difficulty
        generated_this_level: list[TaskSkeleton] = []

        category_counts = Counter({c: 0 for c in config.TASK_CATEGORIES})

        while len(generated_this_level) < needed:
            remaining = needed - len(generated_this_level)

            underrepresented = category_counts.most_common()
            underrepresented.reverse()
            cats_to_fill = [
                c for c, _ in underrepresented[:max(1, remaining // 3 + 1)]
            ]

            batch_prompts: list[tuple[str, str]] = []
            batch_meta: list[tuple[str, int, int]] = []
            for cat in cats_to_fill:
                per_cat = max(1, min(5, remaining // len(cats_to_fill)))
                batch_prompts.append((
                    SKELETON_SYSTEM,
                    _build_skeleton_prompt(cat, difficulty, per_cat, collected_goals),
                ))
                batch_meta.append((cat, difficulty, per_cat))

            raw_texts = sample_text_batch(batch_prompts, temperature=0.75)

            for raw, (cat, diff, _expected) in zip(raw_texts, batch_meta):
                parsed = parse_json_lenient(raw)
                if parsed is None:
                    print(f"    [warn] JSON parse failed for ({cat}, {diff}-step)")
                    continue
                if isinstance(parsed, dict):
                    parsed = [parsed]

                for item in parsed:
                    if not isinstance(item, dict):
                        continue
                    goal = item.get("goal_description", "")
                    if not goal:
                        continue

                    max_sim = max(
                        (bm25_score(goal, g) for g in collected_goals),
                        default=0.0,
                    )
                    if max_sim > config.BM25_DUPLICATE_THRESHOLD:
                        print(f"    [skip] too similar (bm25={max_sim:.2f}): {goal[:50]}")
                        continue

                    skeleton_counter += 1
                    skel = TaskSkeleton(
                        skeleton_id=f"skel_{skeleton_counter:04d}",
                        category=item.get("category", cat),
                        difficulty=item.get("difficulty", diff),
                        goal_description=goal,
                        key_objects=item.get("key_objects", []),
                        rooms=item.get("rooms", []),
                    )
                    generated_this_level.append(skel)
                    collected_goals.append(goal)
                    category_counts[skel.category] += 1

            if len(generated_this_level) >= needed:
                break

        all_skeletons.extend(generated_this_level[:per_difficulty])
        print(f"  difficulty {difficulty}: {len(generated_this_level[:per_difficulty])} skeletons")

    print(f"  Total skeletons generated: {len(all_skeletons)}")
    return all_skeletons


def save_skeletons(skeletons: list[TaskSkeleton], path: str | None = None) -> str:
    path = path or config.SKELETONS_PATH
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump([s.to_dict() for s in skeletons], f, indent=2, ensure_ascii=False)
    print(f"  Saved {len(skeletons)} skeletons -> {path}")
    return path


def load_skeletons(path: str | None = None) -> list[TaskSkeleton]:
    path = path or config.SKELETONS_PATH
    with open(path, "r", encoding="utf-8") as f:
        return [TaskSkeleton.from_dict(d) for d in json.load(f)]
